In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a developer',
    'understand the meaning of words',
    'your videos are good',
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
# Define the vocabulary size
voc_size = 10000

In [7]:
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4139, 5891, 1657, 3359],
 [4139, 5891, 1657, 7281],
 [4139, 4467, 1657, 6230],
 [853, 2960, 4988, 2993, 1313],
 [853, 2960, 4988, 3345],
 [712, 4139, 3785, 1657, 9627],
 [1279, 8617, 8318, 2993]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



In [9]:
import numpy as np

In [10]:
sen_length = 8
embeded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sen_length)
embeded_docs

array([[   0,    0,    0,    0, 4139, 5891, 1657, 3359],
       [   0,    0,    0,    0, 4139, 5891, 1657, 7281],
       [   0,    0,    0,    0, 4139, 4467, 1657, 6230],
       [   0,    0,    0,  853, 2960, 4988, 2993, 1313],
       [   0,    0,    0,    0,  853, 2960, 4988, 3345],
       [   0,    0,    0,  712, 4139, 3785, 1657, 9627],
       [   0,    0,    0,    0, 1279, 8617, 8318, 2993]])

In [11]:
## Feature Representation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sen_length))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embeded_docs)

1/1 [==============================] - 0s 62ms/step


array([[[ 0.01749516, -0.01832283,  0.03994067,  0.02104965,
          0.01969154, -0.03750881, -0.01183932, -0.01231297,
         -0.01479541, -0.01630179],
        [ 0.01749516, -0.01832283,  0.03994067,  0.02104965,
          0.01969154, -0.03750881, -0.01183932, -0.01231297,
         -0.01479541, -0.01630179],
        [ 0.01749516, -0.01832283,  0.03994067,  0.02104965,
          0.01969154, -0.03750881, -0.01183932, -0.01231297,
         -0.01479541, -0.01630179],
        [ 0.01749516, -0.01832283,  0.03994067,  0.02104965,
          0.01969154, -0.03750881, -0.01183932, -0.01231297,
         -0.01479541, -0.01630179],
        [ 0.0140431 , -0.02305248, -0.00424876, -0.02306417,
          0.02891039, -0.03161399,  0.01131944,  0.04944949,
          0.00771327,  0.03851577],
        [ 0.02516908, -0.04449195, -0.02600263,  0.0241269 ,
          0.03670705,  0.04755597, -0.03322129, -0.02271516,
          0.04724637,  0.02733977],
        [-0.00123201, -0.00512923,  0.02698905, -0.0

In [15]:
embeded_docs[0]

array([   0,    0,    0,    0, 4139, 5891, 1657, 3359])

In [16]:
model.predict(embeded_docs[0])

1/1 [==============================] - 0s 58ms/step


array([[ 0.01749516, -0.01832283,  0.03994067,  0.02104965,  0.01969154,
        -0.03750881, -0.01183932, -0.01231297, -0.01479541, -0.01630179],
       [ 0.01749516, -0.01832283,  0.03994067,  0.02104965,  0.01969154,
        -0.03750881, -0.01183932, -0.01231297, -0.01479541, -0.01630179],
       [ 0.01749516, -0.01832283,  0.03994067,  0.02104965,  0.01969154,
        -0.03750881, -0.01183932, -0.01231297, -0.01479541, -0.01630179],
       [ 0.01749516, -0.01832283,  0.03994067,  0.02104965,  0.01969154,
        -0.03750881, -0.01183932, -0.01231297, -0.01479541, -0.01630179],
       [ 0.0140431 , -0.02305248, -0.00424876, -0.02306417,  0.02891039,
        -0.03161399,  0.01131944,  0.04944949,  0.00771327,  0.03851577],
       [ 0.02516908, -0.04449195, -0.02600263,  0.0241269 ,  0.03670705,
         0.04755597, -0.03322129, -0.02271516,  0.04724637,  0.02733977],
       [-0.00123201, -0.00512923,  0.02698905, -0.03279282,  0.03692992,
         0.00233771, -0.01266428, -0.03731631